export interface Product {
  id: string;
  name: string;
  category: 'Prata' | 'Ouro' | 'Envelhecida' | 'Edição Especial' | 'Tradicional' | 'Premium';
  description: string;
  sensoryProfile: string;
  image: string;
  price?: string;
}

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Caraçuípe Extra Premium',
    category: 'Edição Especial',
    description: 'Destilada em alambiques de cobre e armazenada em barris de Carvalho francês por 3 anos e 6 meses.',
    sensoryProfile: 'Aroma de baunilha, chocolate amargo e tabaco. Sabor de nozes e baunilha.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-caracuipe-extrapremium-750ml.png',
  },
  {
    id: '2',
    name: 'Alavanca Estojo Luxo 18 Anos',
    category: 'Edição Especial',
    description: 'Envelhecida em barris de carvalho europeu por 18 anos. Acompanha estojo e taças de cristal.',
    sensoryProfile: 'Magnífica e equilibrada, ideal para momentos de celebração.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-alavanca-estojoluxo-18anos-700ml.png',
  },
  {
    id: '3',
    name: 'Dom Tápparo Extra Premium',
    category: 'Envelhecida',
    description: 'Armazenada 7 anos em Amendoim e envelhecida 3 anos em Carvalho Americano.',
    sensoryProfile: 'Premiadíssima, com notas marcantes de carvalho americano.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-domtapparo-extrapremium-750ml.png',
  },
  {
    id: '4',
    name: 'Major Faria 12 Anos',
    category: 'Edição Especial',
    description: 'Cachaça artesanal de alta qualidade envelhecida por 12 anos, com estojo de madeira.',
    sensoryProfile: 'Perfil amadeirado profundo, suave e persistente.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-majorfaria-12anos-estojomadeira-500ml.png',
  },
  {
    id: '5',
    name: '10 Ouro',
    category: 'Ouro',
    description: 'Cachaça artesanal envelhecida que traz o equilíbrio perfeito entre o frescor e a madeira.',
    sensoryProfile: 'Notas adocicadas e final suave.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-10-ouro-500ml.png',
  },
  {
    id: '6',
    name: 'Acqua Benta Ouro',
    category: 'Ouro',
    description: 'Uma experiência divina em cada gole, com maturação cuidadosa.',
    sensoryProfile: 'Aroma complexo com toques de especiarias.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-acquabenta-ouro-500ml.png',
  },
  {
    id: '7',
    name: 'Adega de Minas',
    category: 'Tradicional',
    description: 'A essência das montanhas mineiras em uma garrafa clássica.',
    sensoryProfile: 'Sabor robusto e tradicional de Minas Gerais.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-adegademinas-700ml.png',
  },
  {
    id: '8',
    name: 'Bassi Ouro',
    category: 'Ouro',
    description: 'Produção limitada com foco na pureza e no sabor refinado da cana.',
    sensoryProfile: 'Leve toque de mel e amêndoas.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-bassi-ouro-670ml.png',
  },
  {
    id: '9',
    name: 'Blend Nordestino',
    category: 'Premium',
    description: 'Um encontro de sabores que celebra a diversidade das madeiras brasileiras.',
    sensoryProfile: 'Equilíbrio entre o doce e o amadeirado.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-blendnordestino-750ml.png',
  },
  {
    id: '10',
    name: 'Cabaré Carvalho',
    category: 'Envelhecida',
    description: 'Famosa pela sua maciez e cor âmbar profunda, resultado do carvalho.',
    sensoryProfile: 'Notas de baunilha e coco.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-cabare-ouro-carvalho-700ml.png',
  },
  {
    id: '11',
    name: 'Calibrina Prata',
    category: 'Prata',
    description: 'Cristalina e pura, ideal para coquetéis ou para apreciar gelada.',
    sensoryProfile: 'Frescor intenso com notas vegetais.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-calibrina-prata-700ml.png',
  },
  {
    id: '12',
    name: 'Biquinha',
    category: 'Tradicional',
    description: 'Uma cachaça que remete às origens, com sabor autêntico e direto.',
    sensoryProfile: 'Final seco e marcante.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-biquinha-600ml.png',
  },
  {
    id: '13',
    name: 'Maria Boa',
    category: 'Tradicional',
    description: 'Cachaça artesanal de sabor suave e aroma equilibrado.',
    sensoryProfile: 'Leve e refrescante.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-mariaboa-300ml.png',
  },
  {
    id: '14',
    name: 'Matraga',
    category: 'Ouro',
    description: 'Envelhecida com maestria para atingir um perfil complexo.',
    sensoryProfile: 'Notas amadeiradas e especiarias.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-matraga-670ml.png',
  },
  {
    id: '15',
    name: 'Middas Reserva',
    category: 'Edição Especial',
    description: 'Cachaça premium com flocos de ouro 23k comestíveis.',
    sensoryProfile: 'Sofisticação extrema e brilho único.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-middas-reserva-700ml.png',
  },
  {
    id: '16',
    name: 'Mineiríssima',
    category: 'Tradicional',
    description: 'A verdadeira cachaça de Minas em embalagem generosa.',
    sensoryProfile: 'Forte, encorpada e autêntica.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-mineirissima-1000ml.png',
  },
  {
    id: '17',
    name: 'Moendão Ouro',
    category: 'Ouro',
    description: 'Tradicional cachaça de alambique com maturação em madeira.',
    sensoryProfile: 'Sabor clássico com final adocicado.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-moendao-ouro-700ml.png',
  },
  {
    id: '18',
    name: 'Monte Alto Prata',
    category: 'Prata',
    description: 'Pureza e frescor em uma cachaça branca de alta qualidade.',
    sensoryProfile: 'Notas de cana fresca e suavidade.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-montealto-prata-600ml.png',
  },
  {
    id: '19',
    name: 'Ouro Goiano',
    category: 'Ouro',
    description: 'O melhor do Cerrado goiano em uma cachaça envelhecida.',
    sensoryProfile: 'Aroma intenso e cor dourada vibrante.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-ourogoiano-750ml.png',
  },
  {
    id: '20',
    name: 'Peruaçu Ouro',
    category: 'Ouro',
    description: 'Cachaça premiada com envelhecimento em madeiras nobres.',
    sensoryProfile: 'Complexidade e elegância no paladar.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-peruacu-ouro-670ml.png',
  },
  {
    id: '21',
    name: 'Pitangui Amburana',
    category: 'Envelhecida',
    description: 'Maturação em Amburana que confere notas adocicadas únicas.',
    sensoryProfile: 'Baunilha, canela e suavidade extrema.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-pitangui-amburana-700ml.png',
  },
  {
    id: '22',
    name: 'Poço da Pedra Prime',
    category: 'Premium',
    description: 'Seleção especial para paladares exigentes.',
    sensoryProfile: 'Equilíbrio perfeito e final longo.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-pocodapedra-prime-500ml.png',
  },
  {
    id: '23',
    name: 'Porto Morretes Premium',
    category: 'Premium',
    description: 'Cachaça orgânica premiada internacionalmente.',
    sensoryProfile: 'Sabor refinado e produção sustentável.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-portomorretes-premium-700ml.png',
  },
  {
    id: '24',
    name: 'Reserva da Dorna',
    category: 'Edição Especial',
    description: 'Lote exclusivo com envelhecimento prolongado.',
    sensoryProfile: 'Riqueza de aromas e sabor aveludado.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-reservadadorna-750ml.png',
  },
  {
    id: '25',
    name: 'Salicana 10 Anos',
    category: 'Edição Especial',
    description: 'Uma década de maturação em garrafa preta especial.',
    sensoryProfile: 'Extrema complexidade e notas de tabaco e couro.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-salicana-10anos-garrafapretaespecial-700ml.png',
  },
  {
    id: '26',
    name: 'Santo Grau Cinco Botas',
    category: 'Premium',
    description: 'Envelhecida em barris de Jerez pelo sistema de solera.',
    sensoryProfile: 'Notas de frutas passas e carvalho.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-santograu-cincobotas-750ml.png',
  },
  {
    id: '27',
    name: 'Seiva Missioneira',
    category: 'Edição Especial',
    description: 'Extra Premium envelhecida por 8 anos em carvalho.',
    sensoryProfile: 'Sabor profundo e aroma amadeirado.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-seivamissioneira-carvalho-8anos-700ml..png',
  },
  {
    id: '28',
    name: 'Soberana Ouro',
    category: 'Ouro',
    description: 'Cachaça de alambique com brilho e sabor soberanos.',
    sensoryProfile: 'Encorpada e marcante.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-soberana-700ml.png',
  },
  {
    id: '29',
    name: 'Tessarollo Ouro',
    category: 'Ouro',
    description: 'Tradição familiar em cada gota desta cachaça envelhecida.',
    sensoryProfile: 'Suave com toques de castanhas.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-tessarolo-ouro-700ml.png',
  },
  {
    id: '30',
    name: 'Alavanca Ouro',
    category: 'Ouro',
    description: 'Cachaça de alambique com maturação equilibrada em madeira.',
    sensoryProfile: 'Notas de baunilha e final persistente.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-alavanca-ouro-700ml.png',
  },
  {
    id: '31',
    name: 'Brejo dos Bois',
    category: 'Tradicional',
    description: 'Cachaça clássica que preserva o sabor autêntico da cana.',
    sensoryProfile: 'Frescor e suavidade.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-brejodosbois-tradicional-700ml.png',
  },
  {
    id: '32',
    name: 'Buteco do Jay',
    category: 'Envelhecida',
    description: 'Envelhecida em Carvalho para um paladar moderno e sofisticado.',
    sensoryProfile: 'Toques de chocolate e madeira.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-butecodojay-carvalho-700ml.png',
  },
  {
    id: '33',
    name: 'Central do Brasil',
    category: 'Prata',
    description: 'Pureza absoluta em uma cachaça branca de alto padrão.',
    sensoryProfile: 'Cristalina com aroma de cana fresca.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-centraldobrasil-prata-700ml.png',
  },
  {
    id: '34',
    name: 'Chico Mineiro',
    category: 'Prata',
    description: 'A tradição mineira em uma versão leve e versátil.',
    sensoryProfile: 'Suave e ideal para caipirinhas.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-chicomineiro-prata-355ml.png',
  },
  {
    id: '35',
    name: 'Clarinha de Minas',
    category: 'Tradicional',
    description: 'Sabor que remete às fazendas coloniais de Minas Gerais.',
    sensoryProfile: 'Doce e aveludada.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-clarinhademinas-700ml.png',
  },
  {
    id: '36',
    name: 'Cortarelli Ipê',
    category: 'Envelhecida',
    description: 'Maturação em Ipê, madeira brasileira que confere cor e sabor únicos.',
    sensoryProfile: 'Notas florais e amadeiradas leves.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-cortarelli-ipe-700ml.png',
  },
  {
    id: '37',
    name: 'DLourdes Ouro',
    category: 'Ouro',
    description: 'Elegância e tradição em uma cachaça de cor dourada intensa.',
    sensoryProfile: 'Aroma de amêndoas e baunilha.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-dlourdes-ouro-670ml.png',
  },
  {
    id: '38',
    name: 'Danada di Boa',
    category: 'Envelhecida',
    description: 'Blend de três madeiras que cria uma complexidade inigualável.',
    sensoryProfile: 'Frutas secas e especiarias.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-danadadiboa-iiimadeiras-600ml.png',
  },
  {
    id: '39',
    name: 'Do Imperador',
    category: 'Ouro',
    description: 'Digna da realeza, com envelhecimento primoroso.',
    sensoryProfile: 'Sabor nobre e persistente.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-doimperador-700ml.png',
  },
  {
    id: '40',
    name: 'Doce Paixão',
    category: 'Tradicional',
    description: 'Cachaça que conquista pelo seu equilíbrio e doçura natural.',
    sensoryProfile: 'Suave e apaixonante.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-docepaixao-600ml.png',
  },
  {
    id: '41',
    name: 'Dois Bois Prata',
    category: 'Prata',
    description: 'Força e pureza em uma cachaça branca de alambique.',
    sensoryProfile: 'Aroma limpo e final refrescante.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-doisbois-prata-670ml.png',
  },
  {
    id: '42',
    name: 'Dom Cabral',
    category: 'Ouro',
    description: 'Maturação em barris selecionados para um perfil clássico.',
    sensoryProfile: 'Notas de mel e carvalho.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-domcabral-ouro-700ml.png',
  },
  {
    id: '43',
    name: 'Dom Patas',
    category: 'Tradicional',
    description: 'Cachaça artesanal com personalidade forte e marcante.',
    sensoryProfile: 'Sabor encorpado.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-dompatas-500ml.png',
  },
  {
    id: '44',
    name: 'Dona Beja',
    category: 'Edição Especial',
    description: 'Homenagem à lendária figura mineira, com qualidade extra premium.',
    sensoryProfile: 'Sofisticada e histórica.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-donabeja-extrapremium-500ml.png',
  },
  {
    id: '45',
    name: 'Du Botti 25 Anos',
    category: 'Edição Especial',
    description: 'Um quarto de século de envelhecimento em garrafa de louça.',
    sensoryProfile: 'Raridade absoluta e sabor eterno.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-dubotti-25anos-louca-120ml.png',
  },
  {
    id: '46',
    name: 'Engenho d\'Ouro',
    category: 'Prata',
    description: 'Cachaça branca de Paraty, com tradição secular.',
    sensoryProfile: 'Frescor marítimo e doçura da cana.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-engenho-douro-prata-700ml.png',
  },
  {
    id: '47',
    name: 'Escorrega Gold',
    category: 'Ouro',
    description: 'Famosa pela sua descida macia e sabor envolvente.',
    sensoryProfile: 'Aveludada e brilhante.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-escorrega-700ml.png',
  },
  {
    id: '48',
    name: 'Estância Moretti',
    category: 'Envelhecida',
    description: 'Blend de 4 madeiras que resulta em um equilíbrio perfeito.',
    sensoryProfile: 'Complexidade de aromas e sabores.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-estanciamoretti-4madeiras-500ml.png',
  },
  {
    id: '49',
    name: 'Excelência Carvalho',
    category: 'Envelhecida',
    description: 'Garrafa especial contendo o melhor do carvalho europeu.',
    sensoryProfile: 'Notas de baunilha e especiarias finas.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-excelencia-garrafaespecial-carvalho-750ml.png',
  },
  {
    id: '50',
    name: 'Fagulha',
    category: 'Tradicional',
    description: 'Cachaça que acende o paladar com sua autenticidade.',
    sensoryProfile: 'Sabor vibrante e tradicional.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-fagulha-860ml.png',
  },
  {
    id: '51',
    name: 'Ferradura de Ouro',
    category: 'Tradicional',
    description: 'Sorte e sabor em uma cachaça clássica de alambique.',
    sensoryProfile: 'Equilibrada e honesta.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-ferraduradeouro-150ml.png',
  },
  {
    id: '52',
    name: 'Flor da Montanha',
    category: 'Prata',
    description: 'Pureza das alturas em uma cachaça branca impecável.',
    sensoryProfile: 'Leve e cristalina.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-flordamontanha-prata-700ml.png',
  },
  {
    id: '53',
    name: 'Flor de Salinas',
    category: 'Envelhecida',
    description: 'A alma de Salinas em uma cachaça envelhecida em Amburana.',
    sensoryProfile: 'Aroma floral e sabor adocicado.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-flordesalinas-umburana-670ml.png',
  },
  {
    id: '54',
    name: 'Formosa Extra Premium',
    category: 'Edição Especial',
    description: 'Cachaça de luxo envelhecida em Carvalho para momentos únicos.',
    sensoryProfile: 'Elegância e profundidade.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-formosa-carvalho-700ml.png',
  },
  {
    id: '55',
    name: 'Fortaleza',
    category: 'Tradicional',
    description: 'Força e tradição em uma cachaça que honra suas raízes.',
    sensoryProfile: 'Sabor robusto.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-fortaleza-700ml.png',
  },
  {
    id: '56',
    name: 'Gaivota',
    category: 'Tradicional',
    description: 'Leveza e liberdade em uma cachaça artesanal clássica.',
    sensoryProfile: 'Suave e fácil de apreciar.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-gaivota-600ml.png',
  },
  {
    id: '57',
    name: 'Garrancho Ouro',
    category: 'Ouro',
    description: 'Cachaça envelhecida com cor de ouro velho e sabor marcante.',
    sensoryProfile: 'Notas amadeiradas intensas.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-garrancho-ouro-670ml.png',
  },
  {
    id: '58',
    name: 'Ginga Brasil',
    category: 'Premium',
    description: 'A alegria brasileira engarrafada com sofisticação.',
    sensoryProfile: 'Equilibrada e vibrante.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-gingabrasil-700ml.png',
  },
  {
    id: '59',
    name: 'Gotas da Moenda',
    category: 'Ouro',
    description: 'Cada gota traz a essência do melhor da cana-de-açúcar.',
    sensoryProfile: 'Doce e suave.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-gotasdamoenda-ouro-700ml.png',
  },
  {
    id: '60',
    name: 'Graciosa Ouro',
    category: 'Ouro',
    description: 'Cachaça envelhecida que encanta pela sua delicadeza.',
    sensoryProfile: 'Aroma sutil e sabor elegante.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-graciosa-ouro-670ml.png',
  },
  {
    id: '61',
    name: 'Gran Nonno',
    category: 'Ouro',
    description: 'Homenagem aos antepassados com uma cachaça de ouro.',
    sensoryProfile: 'Sabor que atravessa gerações.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-grannonno-ouro-700ml.png',
  },
  {
    id: '62',
    name: 'Granraiz Signature',
    category: 'Edição Especial',
    description: 'Assinatura de mestre em uma cachaça envelhecida em Carvalho.',
    sensoryProfile: 'Complexidade e distinção.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-granraiz-signature-carvalho-750ml.png',
  },
  {
    id: '63',
    name: 'Guaraciama Ouro',
    category: 'Ouro',
    description: 'Tradição secular em uma cachaça de cor e sabor inconfundíveis.',
    sensoryProfile: 'Notas de madeira e mel.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-guaraciama-670ml.png',
  },
  {
    id: '64',
    name: 'Havaninha',
    category: 'Tradicional',
    description: 'A pequena gigante de Salinas, famosa mundialmente.',
    sensoryProfile: 'Sabor intenso e inesquecível.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-havaninha-600ml.png',
  },
  {
    id: '65',
    name: 'Herança Mineira',
    category: 'Prata',
    description: 'O legado de Minas em uma cachaça branca pura e vibrante.',
    sensoryProfile: 'Frescor da cana e suavidade.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-herancamineira-prata-700ml.png',
  },
  {
    id: '66',
    name: 'Insinuante Louça',
    category: 'Edição Especial',
    description: 'Garrafa de louça ovalada que guarda uma cachaça preciosa.',
    sensoryProfile: 'Macia e envolvente.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-insinuante-loucaovalada-670ml.png',
  },
  {
    id: '67',
    name: 'Jeceaba',
    category: 'Tradicional',
    description: 'Cachaça artesanal clássica em embalagem prática.',
    sensoryProfile: 'Sabor direto e autêntico.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-jeceaba-160ml.png',
  },
  {
    id: '68',
    name: 'Lajeado de Minas',
    category: 'Ouro',
    description: 'Envelhecida nas terras altas de Minas para um sabor superior.',
    sensoryProfile: 'Notas amadeiradas e final doce.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-lajeadodeminas-ouro-670ml.png',
  },
  {
    id: '69',
    name: 'Lenda do Chapadão',
    category: 'Tradicional',
    description: 'Uma história de sabor contada em cada garrafa.',
    sensoryProfile: 'Mística e saborosa.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-lendadochapadao-700ml.png',
  },
  {
    id: '70',
    name: 'Liberdade Ouro',
    category: 'Ouro',
    description: 'Cachaça que celebra a liberdade com seu sabor dourado.',
    sensoryProfile: 'Leve e harmoniosa.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-liberdade-ouro-670ml.png',
  },
  {
    id: '71',
    name: 'Lua Branca',
    category: 'Tradicional',
    description: 'Cachaça que brilha como o luar, com pureza e suavidade.',
    sensoryProfile: 'Refrescante e pura.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-luabranca-600ml.png',
  },
  {
    id: '72',
    name: 'Luana',
    category: 'Tradicional',
    description: 'Artesanal de alta qualidade para o dia a dia.',
    sensoryProfile: 'Sabor equilibrado.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-luana-600ml.png',
  },
  {
    id: '73',
    name: 'Macena Ouro',
    category: 'Ouro',
    description: 'Maturação cuidadosa para um perfil sensorial rico.',
    sensoryProfile: 'Notas de baunilha e coco.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-macena-ouro-670ml.png',
  },
  {
    id: '74',
    name: 'Manda Chuva',
    category: 'Tradicional',
    description: 'Cachaça com autoridade e sabor inconfundível.',
    sensoryProfile: 'Forte e marcante.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-mandachuva-700ml.png',
  },
  {
    id: '75',
    name: 'Mandaguahy Ouro',
    category: 'Ouro',
    description: 'Tradição do interior paulista em uma cachaça envelhecida.',
    sensoryProfile: 'Suave e amadeirada.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-mandaguahy-700ml.png',
  },
  {
    id: '76',
    name: 'Maria Bacana',
    category: 'Tradicional',
    description: 'Cachaça alegre e vibrante, perfeita para celebrações.',
    sensoryProfile: 'Saborosa e leve.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-mariabacana-700ml.png',
  },
  {
    id: '77',
    name: 'Maria João',
    category: 'Tradicional',
    description: 'Cachaça artesanal clássica em miniatura.',
    sensoryProfile: 'Autêntica e prática.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-mariajoao-50ml.png',
  },
  {
    id: '78',
    name: 'Matuta Umburana',
    category: 'Envelhecida',
    description: 'A famosa paraibana em sua versão envelhecida em Umburana.',
    sensoryProfile: 'Notas florais e doçura característica.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-matuta-umburana-250ml.png',
  },
  {
    id: '79',
    name: 'Middas Golden Touch',
    category: 'Edição Especial',
    description: 'O toque de ouro em uma cachaça de luxo incomparável.',
    sensoryProfile: 'Brilho e sofisticação.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-middas-700ml..png',
  },
  {
    id: '80',
    name: 'Minas Ouro',
    category: 'Ouro',
    description: 'O ouro líquido das montanhas de Minas Gerais.',
    sensoryProfile: 'Cor âmbar e sabor amadeirado.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-minasouro-670ml.png',
  },
  {
    id: '81',
    name: 'Moicana Ouro',
    category: 'Ouro',
    description: 'Personalidade e tradição em uma cachaça envelhecida.',
    sensoryProfile: 'Sabor intenso.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-moicana-ouro-160ml.png',
  },
  {
    id: '82',
    name: 'Monte Cana',
    category: 'Tradicional',
    description: 'Cachaça de alambique com o puro sabor da cana.',
    sensoryProfile: 'Honesta e equilibrada.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-montecana-600ml.png',
  },
  {
    id: '83',
    name: 'Morro Vermelho',
    category: 'Ouro',
    description: 'Cor de fogo e sabor de terra em uma cachaça envelhecida.',
    sensoryProfile: 'Forte e persistente.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-morrovermelho-600ml.png',
  },
  {
    id: '84',
    name: 'Murano Kit',
    category: 'Edição Especial',
    description: 'Kit exclusivo com garrafas de design único.',
    sensoryProfile: 'Beleza e sabor em harmonia.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-murano-kitgarrafas-500ml.png',
  },
  {
    id: '85',
    name: 'Opinião',
    category: 'Tradicional',
    description: 'Cachaça com voz própria e sabor autêntico.',
    sensoryProfile: 'Sabor que marca presença.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-opiniao-970ml.png',
  },
  {
    id: '86',
    name: 'Palmital',
    category: 'Tradicional',
    description: 'Cachaça artesanal clássica do interior.',
    sensoryProfile: 'Suave e tradicional.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-palmital-160ml.png',
  },
  {
    id: '87',
    name: 'Pinga Minas',
    category: 'Envelhecida',
    description: 'Envelhecida em Carvalho para um paladar refinado.',
    sensoryProfile: 'Notas de madeira e baunilha.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-pingaminas-750ml.png',
  },
  {
    id: '88',
    name: 'Pinguinha',
    category: 'Tradicional',
    description: 'A dose perfeita de tradição em miniatura.',
    sensoryProfile: 'Autêntica e prática.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-pinguinha-50ml.png',
  },
  {
    id: '89',
    name: 'Pirapora Carvalho',
    category: 'Envelhecida',
    description: 'O sabor do Rio São Francisco em uma cachaça envelhecida.',
    sensoryProfile: 'Notas de carvalho e final longo.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-pirapora-carvalho-750ml.png',
  },
  {
    id: '90',
    name: 'Playboy Premium',
    category: 'Premium',
    description: 'Estilo e qualidade em uma cachaça premium.',
    sensoryProfile: 'Sofisticada e moderna.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-playboy-premium-750ml.png',
  },
  {
    id: '91',
    name: 'Poço da Pedra Jequitibá',
    category: 'Envelhecida',
    description: 'Maturação em Jequitibá-Rosa, a madeira rainha das cachaças.',
    sensoryProfile: 'Leveza e elegância floral.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-pocodapedra-jequitiba-700ml.png',
  },
  {
    id: '92',
    name: 'Primeira Dama',
    category: 'Prata',
    description: 'Elegância e pureza em uma cachaça branca de destaque.',
    sensoryProfile: 'Suave e cristalina.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-primeiradama-700ml.png',
  },
  {
    id: '93',
    name: 'Quinta do Cedro',
    category: 'Ouro',
    description: 'Envelhecida com o cuidado das quintas tradicionais.',
    sensoryProfile: 'Notas de cedro e mel.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-quintadocedro-ouro-670ml.png',
  },
  {
    id: '94',
    name: 'Quizumba',
    category: 'Tradicional',
    description: 'Cachaça com ritmo e sabor brasileiro.',
    sensoryProfile: 'Vibrante e saborosa.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-quizumba-600ml.png',
  },
  {
    id: '95',
    name: 'Rainha do Vale',
    category: 'Tradicional',
    description: 'A majestade do vale em uma cachaça clássica.',
    sensoryProfile: 'Sabor real e autêntico.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-rainhadovale-classica-1000ml.png',
  },
  {
    id: '96',
    name: 'Reserva do Nosco',
    category: 'Edição Especial',
    description: 'Lote especial com maturação diferenciada.',
    sensoryProfile: 'Complexidade e exclusividade.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-reservadonosco-edicaoespecial-700ml.png',
  },
  {
    id: '97',
    name: 'Ribeiro da Silva',
    category: 'Tradicional',
    description: 'Tradição familiar em cada garrafa.',
    sensoryProfile: 'Sabor clássico de alambique.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-ribeirodasilva-700ml.png',
  },
  {
    id: '98',
    name: 'Rio de Engenho',
    category: 'Premium',
    description: 'Cachaça bojuda com sabor que flui como um rio.',
    sensoryProfile: 'Suave e refrescante.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-riodoengenho-gfbojuda-700ml-scaled.jpg',
  },
  {
    id: '99',
    name: 'Sabiá',
    category: 'Tradicional',
    description: 'O canto da cachaça artesanal em uma garrafa prática.',
    sensoryProfile: 'Leve e melodiosa no paladar.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-sabia-300ml.png',
  },
  {
    id: '100',
    name: 'Saboeiro Umburana',
    category: 'Envelhecida',
    description: 'Tradição nordestina envelhecida em Umburana.',
    sensoryProfile: 'Notas de canela e especiarias.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-saboeiro-umburana-1000ml.png',
  },
  {
    id: '101',
    name: 'Sagra',
    category: 'Tradicional',
    description: 'Cachaça artesanal clássica em miniatura.',
    sensoryProfile: 'Sabor sagrado.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-sagra-150ml.png',
  },
  {
    id: '102',
    name: 'Salicana Cipó',
    category: 'Envelhecida',
    description: 'Maturação em Cipó-Cravo para um sabor exótico e único.',
    sensoryProfile: 'Notas de cravo e especiarias.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-salicana-cipo-1000ml.png',
  },
  {
    id: '103',
    name: 'Salimoc',
    category: 'Tradicional',
    description: 'Cachaça de Salinas com o sabor que o mundo conhece.',
    sensoryProfile: 'Intensa e autêntica.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-salimoc-600ml.png',
  },
  {
    id: '104',
    name: 'Salinense',
    category: 'Tradicional',
    description: 'A essência de Salinas em cada gota.',
    sensoryProfile: 'Sabor clássico da capital da cachaça.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-salinense-670ml.png',
  },
  {
    id: '105',
    name: 'Salivana',
    category: 'Tradicional',
    description: 'Cachaça artesanal em dose única.',
    sensoryProfile: 'Saborosa e prática.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-salivana-50ml.png',
  },
  {
    id: '106',
    name: 'Santo Grau Pedro Ximenes',
    category: 'Premium',
    description: 'Envelhecida em barris que contiveram vinho Pedro Ximénez.',
    sensoryProfile: 'Doçura natural e notas de passas.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-santograu-pedroximenes-750ml.png',
  },
  {
    id: '107',
    name: 'São Miguel',
    category: 'Tradicional',
    description: 'Cachaça artesanal clássica em miniatura.',
    sensoryProfile: 'Sabor tradicional.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-saomiguel-160ml.png',
  },
  {
    id: '108',
    name: 'Saramandaia',
    category: 'Prata',
    description: 'Pureza e tradição em uma cachaça branca de destaque.',
    sensoryProfile: 'Suave e cristalina.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-saramandaia-prata-700ml.png',
  },
  {
    id: '109',
    name: 'Seleta Atlético',
    category: 'Tradicional',
    description: 'Edição especial para os apaixonados pelo Galo.',
    sensoryProfile: 'Sabor campeão.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-seleta-atletico-670ml.png',
  },
  {
    id: '110',
    name: 'Serrinha Rapadura',
    category: 'Tradicional',
    description: 'Cachaça com o toque doce e rústico da rapadura.',
    sensoryProfile: 'Doce e encorpada.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-serrinha-rapadura-670ml.png',
  },
  {
    id: '111',
    name: 'Sinhá Brasil',
    category: 'Tradicional',
    description: 'Cachaça pura que celebra a alma brasileira.',
    sensoryProfile: 'Autêntica e vibrante.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-sinhabrasil-pura-750ml.png',
  },
  {
    id: '112',
    name: 'Siqueira',
    category: 'Tradicional',
    description: 'Tradição e qualidade em uma cachaça artesanal clássica.',
    sensoryProfile: 'Sabor equilibrado.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-siqueira-700ml.png',
  },
  {
    id: '113',
    name: 'Solar Branca',
    category: 'Prata',
    description: 'Cachaça branca pura que brilha como o sol.',
    sensoryProfile: 'Frescor e suavidade.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-solar-branca-670ml.png',
  },
  {
    id: '114',
    name: 'Spiral',
    category: 'Tradicional',
    description: 'Cachaça moderna com raízes tradicionais.',
    sensoryProfile: 'Equilibrada e versátil.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-spiral-700ml.png',
  },
  {
    id: '115',
    name: 'Tabuleira',
    category: 'Tradicional',
    description: 'Cachaça artesanal clássica do interior.',
    sensoryProfile: 'Sabor rústico e autêntico.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-tabuleira-670ml.png',
  },
  {
    id: '116',
    name: 'Taió',
    category: 'Tradicional',
    description: 'Cachaça com personalidade e sabor marcante.',
    sensoryProfile: 'Intensa e saborosa.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-taio-670ml.png',
  },
  {
    id: '117',
    name: 'Thimotina',
    category: 'Tradicional',
    description: 'Tradição e qualidade em uma cachaça artesanal de destaque.',
    sensoryProfile: 'Sabor equilibrado.',
    image: 'https://savanacachacas.com.br/wp-content/uploads/2023/02/cachaca-thimotina-700ml.png',
  },
];
